Neos:
  MetaData:
    defaultEelContext:
      Array: 'TYPO3\Eel\Helper\ArrayHelper'

    metaDataMapping:
      title: '${String.crop(asset.Title || iptc.Title || exif.imageDescription, 255)}'
      caption: '${asset.Caption || iptc.Description}'
      tags: '${Array.concat(asset.tags || [], iptc.keywords || [])}'
